# name: mincatflow
channels:
  - conda-forge
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py310h25320af_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_14
  - libgcc-ng=15.2.0=h69a702a_14
  - libgomp=15.2.0=he0feb66_14
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_14
  - libstdcxx-ng=15.2.0=hdf11a46_14
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyh8b19718_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310h139afa4_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_ha0e22de_103
  - tornado=6.5.2=py310h7c4b9e2_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhcf101f3_1
  - zstd=1.5.7=h3691f8a_5
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - ase==3.26.0
      - ase-db-backends==0.11.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bibtexparser==1.4.3
      - black==22.3.0
      - bleach==6.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - clusterscope==0.0.18
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - defusedxml==0.7.1
      - dill==0.4.0
      - e3nn==0.5.8
      - einops==0.8.1
      - fairchem-core==2.12.0
      - fastjsonschema==2.21.2
      - filelock==3.20.1
      - fonttools==4.61.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.2
      - hydra-core==1.3.2
      - idna==3.11
      - iniconfig==2.3.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - lmdb==1.6.2
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mistune==3.1.4
      - monty==2025.3.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - narwhals==2.13.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.3
      - nglview==4.0
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numpy==2.1.2
      # - nvidia-cublas-cu11==11.11.3.6
      # - nvidia-cublas-cu12==12.8.4.1
      # - nvidia-cuda-cupti-cu11==11.8.87
      # - nvidia-cuda-cupti-cu12==12.8.90
      # - nvidia-cuda-nvrtc-cu11==11.8.89
      # - nvidia-cuda-nvrtc-cu12==12.8.93
      # - nvidia-cuda-runtime-cu11==11.8.89
      # - nvidia-cuda-runtime-cu12==12.8.90
      # - nvidia-cudnn-cu11==9.1.0.70
      # - nvidia-cudnn-cu12==9.10.2.21
      # - nvidia-cufft-cu11==10.9.0.58
      # - nvidia-cufft-cu12==11.3.3.83
      # - nvidia-cufile-cu12==1.13.1.3
      # - nvidia-curand-cu11==10.3.0.86
      # - nvidia-curand-cu12==10.3.9.90
      # - nvidia-cusolver-cu11==11.4.1.48
      # - nvidia-cusolver-cu12==11.7.3.90
      # - nvidia-cusparse-cu11==11.7.5.86
      # - nvidia-cusparse-cu12==12.5.8.93
      # - nvidia-cusparselt-cu12==0.7.1
      # - nvidia-ml-py==13.580.82
      # - nvidia-nccl-cu11==2.21.5
      # - nvidia-nccl-cu12==2.27.3
      # - nvidia-nvjitlink-cu12==12.8.93
      # - nvidia-nvtx-cu11==11.8.86
      # - nvidia-nvtx-cu12==12.8.90
      - nvitop==1.6.1
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - orjson==3.11.4
      - overrides==7.7.0
      - palettable==3.3.3
      - pandarallel==1.6.5
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pathos==0.3.4
      - pathspec==0.12.1
      - pebble==5.1.3
      - pillow==11.3.0
      - platformdirs==4.5.0
      - plotly==6.5.0
      - pluggy==1.6.0
      - pox==0.3.6
      - ppft==1.7.7
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - protobuf==6.33.1
      - psycopg2-binary==2.9.11
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      # - pyg-lib==0.5.0+pt28cu126
      - pymatgen==2025.10.7
      - pymysql==1.1.2
      - pyparsing==3.2.5
      - pyre-extensions==0.0.32
      - pytest==9.0.1
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - scipy==1.15.3
      - send2trash==1.8.3
      - sentry-sdk==2.46.0
      - shellingham==1.5.4
      - smact==3.2.0
      - smmap==5.0.2
      - soupsieve==2.8
      - spglib==2.6.0
      - submitit==1.5.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.3.0
      # - torch==2.8.0+cu126
      # - torch-cluster==1.6.3+pt28cu126
      # - torch-geometric==2.7.0
      # - torch-scatter==2.1.2+pt28cu126
      # - torch-sparse==0.6.18+pt28cu126
      # - torch-spline-conv==1.2.2+pt28cu126
      # - torchaudio==2.8.0+cu126
      # - torchmetrics==1.8.2
      # - torchtnt==0.2.4
      # - torchvision==0.23.0+cu126
      - tqdm==4.67.1
      - triton==3.4.0
      - typer-slim==0.20.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uncertainties==3.2.3
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wandb==0.23.1
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - xxhash==3.6.0
      - yarl==1.22.0