# Main configuration file for EfficientCatGen

expname: effcatgen

# Metadata
core:
  version: 0.0.1
  tags:
    - ${now:%Y-%m-%d}
    - ${expname}

# Hydra configuration
hydra:
  run:
    dir: /home/jovyan/mk-catgen-ckpts/${expname}

  sweep:
    dir: /home/jovyan/mk-catgen-ckpts/multirun/${now:%Y-%m-%d}/${expname}
    subdir: ${hydra.job.num}_${hydra.job.id}

  job:
    env_set:
      WANDB_START_METHOD: thread

# Include other configs
defaults:
  - data: default
  - logging: default
  - model: default
  - optim: default
  - train: default
